name: yolo
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
  - pyg
dependencies:
  - python=3.8
  - pip
  - matplotlib
  - numpy
  - pytorch
  - torchvision
  - opencv
  - pillow
  - pyyaml
  - requests
  - scipy
  - tqdm
  - tensorboard
  - pandas
  - seaborn
  - pip:
    - thop
  #   - tb-nightly
  #   - pdbpp
      # - opencv-python
